newVariables = {

"Event.Number": "Event_number",
"Event.ReadTime": "Event_readtime",
"Event.ProcTime": "Event_proctime",

#"LHCOEvent.Event": "LHCOEvent_event",
#"LHCOEvent.Trigger": "LHCOEvent.Trigger",

#"LHEFEvent.Event": "LHEFEvent_event",
#"LHEFEvent.ProcessID": "LHEFEvent_processid",
#"LHEFEvent.Weight": "LHEFEvent_weight",
#"LHEFEvent.ScalePDF": "LHEFEvent_scalepdf",
#"LHEFEvent.AlphaQED": "LHEFEvent_alphaqed",
#"LHEFEvent.AlphaQCD": "LHEFEvent_alphaqcd",

#"LHEFWeight.ID": "LHEFWeight_id",
#"LHEFWeight.weight": "LHEFWeight_weight",

#"HepMCEvent.Event": "HepMCEvent_event",
#"HepMCEvent.ProcessID": "HepMCEvent_processid",
#"HepMCEvent.MPI": "HepMCEvent_mpi",
#"HepMCEvent.Weight": "HepMCEvent_weight",
#"HepMCEvent.Scale": "HepMCEvent_scale",
#"HepMCEvent.AlphaQED": "HepMCEvent_alphaqed",
#"HepMCEvent.AlphaQCD": "HepMCEvent_aphaqcd",
#"HepMCEvent.ID1": "HepMCEvent_id1",
#"HepMCEvent.ID2": "HepMCEvent_id2",
#"HepMCEvent.X1": "HepMCEvent_x1",
#"HepMCEvent.X2": "HepMCEvent_x2",
#"HepMCEvent.ScalePDF": "HepMCEvent_scalepdf",
#"HepMCEvent.PDF1": "HepMCEvent_pdf1",
#"HepMCEvent.PDF2": "HepMCEvent_pdf2",

"MissingET.MET": "MET_met",
"MissingET.Eta": "MET_eta",
"MissingET.Phi": "MET_phi",

"PhotonTight.PT": "Photon_pt",
"PhotonTight.Eta": "Photon_eta",
"PhotonTight.Phi": "Photon_phi",
#"PhotonTight.E": "PhotonTight_e",
"PhotonTight.T": "Photon_t",
"PhotonTight.EhadOverEem": "Photon_ehadovereem",
#"PhotonTight.Particles": "PhotonTight_particles",
"PhotonTight.IsolationVar": "Photon_isolationvar",
"PhotonTight.IsolationVarRhoCorr": "Photon_isolationvarrhocorr",
"PhotonTight.SumPtCharged": "Photon_sumptcharged",
"PhotonTight.SumPtNeutral": "Photon_sumptneutral",
"PhotonTight.SumPtChargedPU": "Photon_sumptchargedpu",
"PhotonTight.SumPt": "Photon_sumpt",

"MuonTight.PT": "Muon_pt",
"MuonTight.Eta": "Muon_eta",
"MuonTight.Phi": "Muon_phi",
"MuonTight.T": "Muon_t",
"MuonTight.Charge": "Muon_charge",
#"MuonTight.Particle": "MuonTIght_particle",
"MuonTight.IsolationVar": "Muon_isolationvar",
"MuonTight.IsolationVarRhoCorr": "Muon_isolationvarrhocorr",
"MuonTight.SumPtCharged": "Muon_sumptcharged",
"MuonTight.SumPtNeutral": "Muon_sumptneutral",
"MuonTight.SumPtChargedPU": "Muon_sumptchargedpu",
"MuonTight.SumPt": "Muon_sumpt",

"Jet.PT": "Jet_pt",
"Jet.Eta": "Jet_eta",
"Jet.Phi": "Jet_phi",
"Jet.Mass": "Jet_mass",
"Jet.T": "Jet_t",
"Jet.Flavor": "Jet_flavour",
"Jet.FlavorAlgo": "Jet_flavoralgo",
"Jet.FlavorPhys": "Jet_flavorphys",
"Jet.BTag": "Jet_btag",
"Jet.BTagAlgo": "Jet_btagalgo",
"Jet.BTagPhys": "Jet_btagphys",
"Jet.EhadOverEem": "Jet_hoe",
"Jet.NCharged": "Jet_ncharged",
"Jet.NNeutrals": "Jet_nneutrals",


"Electron.PT": "Electron_pt",
"Electron.Eta": "Electron_eta",
"Electron.Phi": "Electron_phi",
"Electron.T": "Electron_t",
"Electron.Charge": "Electron_charge",
"Electron.EhadOverEem": "Electron_hoe",
"Electron.IsolationVar": "Electron_isolationvar",
"Electron.IsolationVarRhoCorr": "Electron_isolationvarrhocorr",
"Electron.SumPtCharged": "Electron_sumptcharged",
"Electron.SumPtNeutral": "Electron_sumptneutral",
"Electron.SumPtChargedPU": "Electron_sumptchargedpu",
"Electron.SumPt": "Electron_sumpt",

"Vertex_size": "Vertex_size"

}
