executable            = script.py
arguments             = $(ClusterId) $(ProcId)
output                = Files/vbfhmumu.$(ClusterId).$(ProcId).out
error                 = Files/vbfhmumu.$(ClusterId).$(ProcId).err
log                   = Files/vbfhmumu.$(ClusterId).log
+JobFlavour           = "longlunch"


should_transfer_files = YES
transfer_input_files  = converter.py, variables.py, samples.py, vbfHmm_powheg.sh, DYToLL_madgraphMLM.sh
queue 


